//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director_Tecnico
    {
        public int id_Director { get; set; }
        public Nullable<int> id_Categoria { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string nacionalidad { get; set; }
        public Nullable<int> titulosGanados { get; set; }
        public Nullable<int> victorias { get; set; }
        public Nullable<int> derrotas { get; set; }
        public Nullable<int> empates { get; set; }
        public string foto_url { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
