//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estadistica()
        {
            this.Jugadores = new List<Jugadores>();
        }
    
        public int idEstadistica { get; set; }
        public int idJugador { get; set; }
        public int idTemporada { get; set; }
        public int partidosJugados { get; set; }
        public int goles { get; set; }
        public int asistencias { get; set; }
        public int tarjetasAmarillas { get; set; }
        public int tarjetasRojas { get; set; }
    
        public virtual Temporada Temporada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Jugadores> Jugadores { get; set; }
    }
}
