//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Equipo
    {
        public int idEquipo { get; set; }
        public string nombre { get; set; }
        public string direccionEstadio { get; set; }
        public string entrenador { get; set; }
        public int añoFundacion { get; set; }
        public string capitan { get; set; }
        public int titulosGanados { get; set; }
    }
}
