//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenador
    {
        public int ID_Entrenador { get; set; }
        public string Nombre_Entrenador { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<int> ID_Categoria { get; set; }
        public string Foto_Entrenador_URL { get; set; }
    
        public virtual CategoriaEquipo CategoriaEquipo { get; set; }
    }
}
