//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ballenitaEntities : DbContext
    {
        public ballenitaEntities()
            : base("name=ballenitaEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaEquipo> CategoriaEquipo { get; set; }
        public virtual DbSet<Entrenador> Entrenador { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<JugadorPartido> JugadorPartido { get; set; }
        public virtual DbSet<Partido> Partido { get; set; }
        public virtual DbSet<Patrocinador> Patrocinador { get; set; }
    }
}
