//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrocinador
    {
        public int ID_Patrocinador { get; set; }
        public string Nombre_Patrocinador { get; set; }
        public string Industria { get; set; }
        public int ID_Categoria { get; set; }
    
        public virtual CategoriaEquipo CategoriaEquipo { get; set; }
    }
}
