//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistaCliente.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JugadorDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class JugadorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicionField;
        
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicionField, value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Equipo {
            get {
                return this.EquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipoField, value) != true)) {
                    this.EquipoField = value;
                    this.RaisePropertyChanged("Equipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntrenadorDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EntrenadorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nacionalidad {
            get {
                return this.NacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadField, value) != true)) {
                    this.NacionalidadField = value;
                    this.RaisePropertyChanged("Nacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Equipo {
            get {
                return this.EquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipoField, value) != true)) {
                    this.EquipoField = value;
                    this.RaisePropertyChanged("Equipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ServicioFutbolSoap")]
    public interface ServicioFutbolSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento JugadoresListaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresLista", ReplyAction="*")]
        VistaCliente.ServiceReference.JugadoresListaResponse JugadoresLista(VistaCliente.ServiceReference.JugadoresListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresLista", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaResponse> JugadoresListaAsync(VistaCliente.ServiceReference.JugadoresListaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresListaByNombre", ReplyAction="*")]
        VistaCliente.ServiceReference.JugadoresListaByNombreResponse JugadoresListaByNombre(VistaCliente.ServiceReference.JugadoresListaByNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresListaByNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaByNombreResponse> JugadoresListaByNombreAsync(VistaCliente.ServiceReference.JugadoresListaByNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento jugador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresAgregar", ReplyAction="*")]
        VistaCliente.ServiceReference.JugadoresAgregarResponse JugadoresAgregar(VistaCliente.ServiceReference.JugadoresAgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresAgregar", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresAgregarResponse> JugadoresAgregarAsync(VistaCliente.ServiceReference.JugadoresAgregarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento jugador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresActualizar", ReplyAction="*")]
        VistaCliente.ServiceReference.JugadoresActualizarResponse JugadoresActualizar(VistaCliente.ServiceReference.JugadoresActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresActualizarResponse> JugadoresActualizarAsync(VistaCliente.ServiceReference.JugadoresActualizarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento equipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresEliminar", ReplyAction="*")]
        VistaCliente.ServiceReference.JugadoresEliminarResponse JugadoresEliminar(VistaCliente.ServiceReference.JugadoresEliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresEliminarResponse> JugadoresEliminarAsync(VistaCliente.ServiceReference.JugadoresEliminarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EntrenadoresListaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresLista", ReplyAction="*")]
        VistaCliente.ServiceReference.EntrenadoresListaResponse EntrenadoresLista(VistaCliente.ServiceReference.EntrenadoresListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresLista", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresListaResponse> EntrenadoresListaAsync(VistaCliente.ServiceReference.EntrenadoresListaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresListaByNombre", ReplyAction="*")]
        VistaCliente.ServiceReference.EntrenadoresListaByNombreResponse EntrenadoresListaByNombre(VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresListaByNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresListaByNombreResponse> EntrenadoresListaByNombreAsync(VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento entrenador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadorAgregar", ReplyAction="*")]
        VistaCliente.ServiceReference.EntrenadorAgregarResponse EntrenadorAgregar(VistaCliente.ServiceReference.EntrenadorAgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadorAgregar", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadorAgregarResponse> EntrenadorAgregarAsync(VistaCliente.ServiceReference.EntrenadorAgregarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento entrenador del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresActualizar", ReplyAction="*")]
        VistaCliente.ServiceReference.EntrenadoresActualizarResponse EntrenadoresActualizar(VistaCliente.ServiceReference.EntrenadoresActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresActualizarResponse> EntrenadoresActualizarAsync(VistaCliente.ServiceReference.EntrenadoresActualizarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento equipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresEliminar", ReplyAction="*")]
        VistaCliente.ServiceReference.EntrenadoresEliminarResponse EntrenadoresEliminar(VistaCliente.ServiceReference.EntrenadoresEliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntrenadoresEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresEliminarResponse> EntrenadoresEliminarAsync(VistaCliente.ServiceReference.EntrenadoresEliminarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento equipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresListaPorEquipo", ReplyAction="*")]
        VistaCliente.ServiceReference.JugadoresListaPorEquipoResponse JugadoresListaPorEquipo(VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JugadoresListaPorEquipo", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaPorEquipoResponse> JugadoresListaPorEquipoAsync(VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarEquiposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarEquipos", ReplyAction="*")]
        VistaCliente.ServiceReference.ListarEquiposResponse ListarEquipos(VistaCliente.ServiceReference.ListarEquiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarEquipos", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.ListarEquiposResponse> ListarEquiposAsync(VistaCliente.ServiceReference.ListarEquiposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerJugadorPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerJugadorPorId", ReplyAction="*")]
        VistaCliente.ServiceReference.ObtenerJugadorPorIdResponse ObtenerJugadorPorId(VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerJugadorPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.ObtenerJugadorPorIdResponse> ObtenerJugadorPorIdAsync(VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresLista", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresListaRequestBody Body;
        
        public JugadoresListaRequest() {
        }
        
        public JugadoresListaRequest(VistaCliente.ServiceReference.JugadoresListaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class JugadoresListaRequestBody {
        
        public JugadoresListaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresListaResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresListaResponseBody Body;
        
        public JugadoresListaResponse() {
        }
        
        public JugadoresListaResponse(VistaCliente.ServiceReference.JugadoresListaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresListaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaResult;
        
        public JugadoresListaResponseBody() {
        }
        
        public JugadoresListaResponseBody(VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaResult) {
            this.JugadoresListaResult = JugadoresListaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresListaByNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresListaByNombre", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresListaByNombreRequestBody Body;
        
        public JugadoresListaByNombreRequest() {
        }
        
        public JugadoresListaByNombreRequest(VistaCliente.ServiceReference.JugadoresListaByNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresListaByNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public JugadoresListaByNombreRequestBody() {
        }
        
        public JugadoresListaByNombreRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresListaByNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresListaByNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresListaByNombreResponseBody Body;
        
        public JugadoresListaByNombreResponse() {
        }
        
        public JugadoresListaByNombreResponse(VistaCliente.ServiceReference.JugadoresListaByNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresListaByNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaByNombreResult;
        
        public JugadoresListaByNombreResponseBody() {
        }
        
        public JugadoresListaByNombreResponseBody(VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaByNombreResult) {
            this.JugadoresListaByNombreResult = JugadoresListaByNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresAgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresAgregar", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresAgregarRequestBody Body;
        
        public JugadoresAgregarRequest() {
        }
        
        public JugadoresAgregarRequest(VistaCliente.ServiceReference.JugadoresAgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresAgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.JugadorDTO jugador;
        
        public JugadoresAgregarRequestBody() {
        }
        
        public JugadoresAgregarRequestBody(VistaCliente.ServiceReference.JugadorDTO jugador) {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresAgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresAgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresAgregarResponseBody Body;
        
        public JugadoresAgregarResponse() {
        }
        
        public JugadoresAgregarResponse(VistaCliente.ServiceReference.JugadoresAgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresAgregarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JugadoresAgregarResult;
        
        public JugadoresAgregarResponseBody() {
        }
        
        public JugadoresAgregarResponseBody(string JugadoresAgregarResult) {
            this.JugadoresAgregarResult = JugadoresAgregarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresActualizar", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresActualizarRequestBody Body;
        
        public JugadoresActualizarRequest() {
        }
        
        public JugadoresActualizarRequest(VistaCliente.ServiceReference.JugadoresActualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresActualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.JugadorDTO jugador;
        
        public JugadoresActualizarRequestBody() {
        }
        
        public JugadoresActualizarRequestBody(VistaCliente.ServiceReference.JugadorDTO jugador) {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresActualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresActualizarResponseBody Body;
        
        public JugadoresActualizarResponse() {
        }
        
        public JugadoresActualizarResponse(VistaCliente.ServiceReference.JugadoresActualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresActualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JugadoresActualizarResult;
        
        public JugadoresActualizarResponseBody() {
        }
        
        public JugadoresActualizarResponseBody(string JugadoresActualizarResult) {
            this.JugadoresActualizarResult = JugadoresActualizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresEliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresEliminar", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresEliminarRequestBody Body;
        
        public JugadoresEliminarRequest() {
        }
        
        public JugadoresEliminarRequest(VistaCliente.ServiceReference.JugadoresEliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresEliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idJugador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string equipo;
        
        public JugadoresEliminarRequestBody() {
        }
        
        public JugadoresEliminarRequestBody(int idJugador, string equipo) {
            this.idJugador = idJugador;
            this.equipo = equipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresEliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresEliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresEliminarResponseBody Body;
        
        public JugadoresEliminarResponse() {
        }
        
        public JugadoresEliminarResponse(VistaCliente.ServiceReference.JugadoresEliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresEliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JugadoresEliminarResult;
        
        public JugadoresEliminarResponseBody() {
        }
        
        public JugadoresEliminarResponseBody(string JugadoresEliminarResult) {
            this.JugadoresEliminarResult = JugadoresEliminarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresLista", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresListaRequestBody Body;
        
        public EntrenadoresListaRequest() {
        }
        
        public EntrenadoresListaRequest(VistaCliente.ServiceReference.EntrenadoresListaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EntrenadoresListaRequestBody {
        
        public EntrenadoresListaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresListaResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresListaResponseBody Body;
        
        public EntrenadoresListaResponse() {
        }
        
        public EntrenadoresListaResponse(VistaCliente.ServiceReference.EntrenadoresListaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadoresListaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.EntrenadorDTO[] EntrenadoresListaResult;
        
        public EntrenadoresListaResponseBody() {
        }
        
        public EntrenadoresListaResponseBody(VistaCliente.ServiceReference.EntrenadorDTO[] EntrenadoresListaResult) {
            this.EntrenadoresListaResult = EntrenadoresListaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresListaByNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresListaByNombre", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresListaByNombreRequestBody Body;
        
        public EntrenadoresListaByNombreRequest() {
        }
        
        public EntrenadoresListaByNombreRequest(VistaCliente.ServiceReference.EntrenadoresListaByNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadoresListaByNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public EntrenadoresListaByNombreRequestBody() {
        }
        
        public EntrenadoresListaByNombreRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresListaByNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresListaByNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresListaByNombreResponseBody Body;
        
        public EntrenadoresListaByNombreResponse() {
        }
        
        public EntrenadoresListaByNombreResponse(VistaCliente.ServiceReference.EntrenadoresListaByNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadoresListaByNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.EntrenadorDTO[] EntrenadoresListaByNombreResult;
        
        public EntrenadoresListaByNombreResponseBody() {
        }
        
        public EntrenadoresListaByNombreResponseBody(VistaCliente.ServiceReference.EntrenadorDTO[] EntrenadoresListaByNombreResult) {
            this.EntrenadoresListaByNombreResult = EntrenadoresListaByNombreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadorAgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadorAgregar", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadorAgregarRequestBody Body;
        
        public EntrenadorAgregarRequest() {
        }
        
        public EntrenadorAgregarRequest(VistaCliente.ServiceReference.EntrenadorAgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadorAgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.EntrenadorDTO entrenador;
        
        public EntrenadorAgregarRequestBody() {
        }
        
        public EntrenadorAgregarRequestBody(VistaCliente.ServiceReference.EntrenadorDTO entrenador) {
            this.entrenador = entrenador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadorAgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadorAgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadorAgregarResponseBody Body;
        
        public EntrenadorAgregarResponse() {
        }
        
        public EntrenadorAgregarResponse(VistaCliente.ServiceReference.EntrenadorAgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadorAgregarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EntrenadorAgregarResult;
        
        public EntrenadorAgregarResponseBody() {
        }
        
        public EntrenadorAgregarResponseBody(string EntrenadorAgregarResult) {
            this.EntrenadorAgregarResult = EntrenadorAgregarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresActualizar", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresActualizarRequestBody Body;
        
        public EntrenadoresActualizarRequest() {
        }
        
        public EntrenadoresActualizarRequest(VistaCliente.ServiceReference.EntrenadoresActualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadoresActualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.EntrenadorDTO entrenador;
        
        public EntrenadoresActualizarRequestBody() {
        }
        
        public EntrenadoresActualizarRequestBody(VistaCliente.ServiceReference.EntrenadorDTO entrenador) {
            this.entrenador = entrenador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresActualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresActualizarResponseBody Body;
        
        public EntrenadoresActualizarResponse() {
        }
        
        public EntrenadoresActualizarResponse(VistaCliente.ServiceReference.EntrenadoresActualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadoresActualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EntrenadoresActualizarResult;
        
        public EntrenadoresActualizarResponseBody() {
        }
        
        public EntrenadoresActualizarResponseBody(string EntrenadoresActualizarResult) {
            this.EntrenadoresActualizarResult = EntrenadoresActualizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresEliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresEliminar", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresEliminarRequestBody Body;
        
        public EntrenadoresEliminarRequest() {
        }
        
        public EntrenadoresEliminarRequest(VistaCliente.ServiceReference.EntrenadoresEliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadoresEliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEntrenador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string equipo;
        
        public EntrenadoresEliminarRequestBody() {
        }
        
        public EntrenadoresEliminarRequestBody(int idEntrenador, string equipo) {
            this.idEntrenador = idEntrenador;
            this.equipo = equipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EntrenadoresEliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EntrenadoresEliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.EntrenadoresEliminarResponseBody Body;
        
        public EntrenadoresEliminarResponse() {
        }
        
        public EntrenadoresEliminarResponse(VistaCliente.ServiceReference.EntrenadoresEliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EntrenadoresEliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EntrenadoresEliminarResult;
        
        public EntrenadoresEliminarResponseBody() {
        }
        
        public EntrenadoresEliminarResponseBody(string EntrenadoresEliminarResult) {
            this.EntrenadoresEliminarResult = EntrenadoresEliminarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresListaPorEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresListaPorEquipo", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresListaPorEquipoRequestBody Body;
        
        public JugadoresListaPorEquipoRequest() {
        }
        
        public JugadoresListaPorEquipoRequest(VistaCliente.ServiceReference.JugadoresListaPorEquipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresListaPorEquipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string equipo;
        
        public JugadoresListaPorEquipoRequestBody() {
        }
        
        public JugadoresListaPorEquipoRequestBody(string equipo) {
            this.equipo = equipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JugadoresListaPorEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JugadoresListaPorEquipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.JugadoresListaPorEquipoResponseBody Body;
        
        public JugadoresListaPorEquipoResponse() {
        }
        
        public JugadoresListaPorEquipoResponse(VistaCliente.ServiceReference.JugadoresListaPorEquipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JugadoresListaPorEquipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaPorEquipoResult;
        
        public JugadoresListaPorEquipoResponseBody() {
        }
        
        public JugadoresListaPorEquipoResponseBody(VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaPorEquipoResult) {
            this.JugadoresListaPorEquipoResult = JugadoresListaPorEquipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarEquipos", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.ListarEquiposRequestBody Body;
        
        public ListarEquiposRequest() {
        }
        
        public ListarEquiposRequest(VistaCliente.ServiceReference.ListarEquiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarEquiposRequestBody {
        
        public ListarEquiposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarEquiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.ListarEquiposResponseBody Body;
        
        public ListarEquiposResponse() {
        }
        
        public ListarEquiposResponse(VistaCliente.ServiceReference.ListarEquiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarEquiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.ArrayOfString ListarEquiposResult;
        
        public ListarEquiposResponseBody() {
        }
        
        public ListarEquiposResponseBody(VistaCliente.ServiceReference.ArrayOfString ListarEquiposResult) {
            this.ListarEquiposResult = ListarEquiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerJugadorPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerJugadorPorId", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.ObtenerJugadorPorIdRequestBody Body;
        
        public ObtenerJugadorPorIdRequest() {
        }
        
        public ObtenerJugadorPorIdRequest(VistaCliente.ServiceReference.ObtenerJugadorPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerJugadorPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idJugador;
        
        public ObtenerJugadorPorIdRequestBody() {
        }
        
        public ObtenerJugadorPorIdRequestBody(int idJugador) {
            this.idJugador = idJugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerJugadorPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerJugadorPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ServiceReference.ObtenerJugadorPorIdResponseBody Body;
        
        public ObtenerJugadorPorIdResponse() {
        }
        
        public ObtenerJugadorPorIdResponse(VistaCliente.ServiceReference.ObtenerJugadorPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerJugadorPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ServiceReference.JugadorDTO ObtenerJugadorPorIdResult;
        
        public ObtenerJugadorPorIdResponseBody() {
        }
        
        public ObtenerJugadorPorIdResponseBody(VistaCliente.ServiceReference.JugadorDTO ObtenerJugadorPorIdResult) {
            this.ObtenerJugadorPorIdResult = ObtenerJugadorPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioFutbolSoapChannel : VistaCliente.ServiceReference.ServicioFutbolSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFutbolSoapClient : System.ServiceModel.ClientBase<VistaCliente.ServiceReference.ServicioFutbolSoap>, VistaCliente.ServiceReference.ServicioFutbolSoap {
        
        public ServicioFutbolSoapClient() {
        }
        
        public ServicioFutbolSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFutbolSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFutbolSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFutbolSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.JugadoresListaResponse VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresLista(VistaCliente.ServiceReference.JugadoresListaRequest request) {
            return base.Channel.JugadoresLista(request);
        }
        
        public VistaCliente.ServiceReference.JugadorDTO[] JugadoresLista() {
            VistaCliente.ServiceReference.JugadoresListaRequest inValue = new VistaCliente.ServiceReference.JugadoresListaRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresListaRequestBody();
            VistaCliente.ServiceReference.JugadoresListaResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresLista(inValue);
            return retVal.Body.JugadoresListaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresListaAsync(VistaCliente.ServiceReference.JugadoresListaRequest request) {
            return base.Channel.JugadoresListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaResponse> JugadoresListaAsync() {
            VistaCliente.ServiceReference.JugadoresListaRequest inValue = new VistaCliente.ServiceReference.JugadoresListaRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresListaRequestBody();
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresListaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.JugadoresListaByNombreResponse VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresListaByNombre(VistaCliente.ServiceReference.JugadoresListaByNombreRequest request) {
            return base.Channel.JugadoresListaByNombre(request);
        }
        
        public VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaByNombre(string nombre) {
            VistaCliente.ServiceReference.JugadoresListaByNombreRequest inValue = new VistaCliente.ServiceReference.JugadoresListaByNombreRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresListaByNombreRequestBody();
            inValue.Body.nombre = nombre;
            VistaCliente.ServiceReference.JugadoresListaByNombreResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresListaByNombre(inValue);
            return retVal.Body.JugadoresListaByNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaByNombreResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresListaByNombreAsync(VistaCliente.ServiceReference.JugadoresListaByNombreRequest request) {
            return base.Channel.JugadoresListaByNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaByNombreResponse> JugadoresListaByNombreAsync(string nombre) {
            VistaCliente.ServiceReference.JugadoresListaByNombreRequest inValue = new VistaCliente.ServiceReference.JugadoresListaByNombreRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresListaByNombreRequestBody();
            inValue.Body.nombre = nombre;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresListaByNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.JugadoresAgregarResponse VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresAgregar(VistaCliente.ServiceReference.JugadoresAgregarRequest request) {
            return base.Channel.JugadoresAgregar(request);
        }
        
        public string JugadoresAgregar(VistaCliente.ServiceReference.JugadorDTO jugador) {
            VistaCliente.ServiceReference.JugadoresAgregarRequest inValue = new VistaCliente.ServiceReference.JugadoresAgregarRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresAgregarRequestBody();
            inValue.Body.jugador = jugador;
            VistaCliente.ServiceReference.JugadoresAgregarResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresAgregar(inValue);
            return retVal.Body.JugadoresAgregarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresAgregarResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresAgregarAsync(VistaCliente.ServiceReference.JugadoresAgregarRequest request) {
            return base.Channel.JugadoresAgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresAgregarResponse> JugadoresAgregarAsync(VistaCliente.ServiceReference.JugadorDTO jugador) {
            VistaCliente.ServiceReference.JugadoresAgregarRequest inValue = new VistaCliente.ServiceReference.JugadoresAgregarRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresAgregarRequestBody();
            inValue.Body.jugador = jugador;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresAgregarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.JugadoresActualizarResponse VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresActualizar(VistaCliente.ServiceReference.JugadoresActualizarRequest request) {
            return base.Channel.JugadoresActualizar(request);
        }
        
        public string JugadoresActualizar(VistaCliente.ServiceReference.JugadorDTO jugador) {
            VistaCliente.ServiceReference.JugadoresActualizarRequest inValue = new VistaCliente.ServiceReference.JugadoresActualizarRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresActualizarRequestBody();
            inValue.Body.jugador = jugador;
            VistaCliente.ServiceReference.JugadoresActualizarResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresActualizar(inValue);
            return retVal.Body.JugadoresActualizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresActualizarResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresActualizarAsync(VistaCliente.ServiceReference.JugadoresActualizarRequest request) {
            return base.Channel.JugadoresActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresActualizarResponse> JugadoresActualizarAsync(VistaCliente.ServiceReference.JugadorDTO jugador) {
            VistaCliente.ServiceReference.JugadoresActualizarRequest inValue = new VistaCliente.ServiceReference.JugadoresActualizarRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresActualizarRequestBody();
            inValue.Body.jugador = jugador;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresActualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.JugadoresEliminarResponse VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresEliminar(VistaCliente.ServiceReference.JugadoresEliminarRequest request) {
            return base.Channel.JugadoresEliminar(request);
        }
        
        public string JugadoresEliminar(int idJugador, string equipo) {
            VistaCliente.ServiceReference.JugadoresEliminarRequest inValue = new VistaCliente.ServiceReference.JugadoresEliminarRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresEliminarRequestBody();
            inValue.Body.idJugador = idJugador;
            inValue.Body.equipo = equipo;
            VistaCliente.ServiceReference.JugadoresEliminarResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresEliminar(inValue);
            return retVal.Body.JugadoresEliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresEliminarResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresEliminarAsync(VistaCliente.ServiceReference.JugadoresEliminarRequest request) {
            return base.Channel.JugadoresEliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresEliminarResponse> JugadoresEliminarAsync(int idJugador, string equipo) {
            VistaCliente.ServiceReference.JugadoresEliminarRequest inValue = new VistaCliente.ServiceReference.JugadoresEliminarRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresEliminarRequestBody();
            inValue.Body.idJugador = idJugador;
            inValue.Body.equipo = equipo;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresEliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.EntrenadoresListaResponse VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresLista(VistaCliente.ServiceReference.EntrenadoresListaRequest request) {
            return base.Channel.EntrenadoresLista(request);
        }
        
        public VistaCliente.ServiceReference.EntrenadorDTO[] EntrenadoresLista() {
            VistaCliente.ServiceReference.EntrenadoresListaRequest inValue = new VistaCliente.ServiceReference.EntrenadoresListaRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresListaRequestBody();
            VistaCliente.ServiceReference.EntrenadoresListaResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresLista(inValue);
            return retVal.Body.EntrenadoresListaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresListaResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresListaAsync(VistaCliente.ServiceReference.EntrenadoresListaRequest request) {
            return base.Channel.EntrenadoresListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresListaResponse> EntrenadoresListaAsync() {
            VistaCliente.ServiceReference.EntrenadoresListaRequest inValue = new VistaCliente.ServiceReference.EntrenadoresListaRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresListaRequestBody();
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresListaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.EntrenadoresListaByNombreResponse VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresListaByNombre(VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest request) {
            return base.Channel.EntrenadoresListaByNombre(request);
        }
        
        public VistaCliente.ServiceReference.EntrenadorDTO[] EntrenadoresListaByNombre(string nombre) {
            VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest inValue = new VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresListaByNombreRequestBody();
            inValue.Body.nombre = nombre;
            VistaCliente.ServiceReference.EntrenadoresListaByNombreResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresListaByNombre(inValue);
            return retVal.Body.EntrenadoresListaByNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresListaByNombreResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresListaByNombreAsync(VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest request) {
            return base.Channel.EntrenadoresListaByNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresListaByNombreResponse> EntrenadoresListaByNombreAsync(string nombre) {
            VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest inValue = new VistaCliente.ServiceReference.EntrenadoresListaByNombreRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresListaByNombreRequestBody();
            inValue.Body.nombre = nombre;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresListaByNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.EntrenadorAgregarResponse VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadorAgregar(VistaCliente.ServiceReference.EntrenadorAgregarRequest request) {
            return base.Channel.EntrenadorAgregar(request);
        }
        
        public string EntrenadorAgregar(VistaCliente.ServiceReference.EntrenadorDTO entrenador) {
            VistaCliente.ServiceReference.EntrenadorAgregarRequest inValue = new VistaCliente.ServiceReference.EntrenadorAgregarRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadorAgregarRequestBody();
            inValue.Body.entrenador = entrenador;
            VistaCliente.ServiceReference.EntrenadorAgregarResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadorAgregar(inValue);
            return retVal.Body.EntrenadorAgregarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadorAgregarResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadorAgregarAsync(VistaCliente.ServiceReference.EntrenadorAgregarRequest request) {
            return base.Channel.EntrenadorAgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadorAgregarResponse> EntrenadorAgregarAsync(VistaCliente.ServiceReference.EntrenadorDTO entrenador) {
            VistaCliente.ServiceReference.EntrenadorAgregarRequest inValue = new VistaCliente.ServiceReference.EntrenadorAgregarRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadorAgregarRequestBody();
            inValue.Body.entrenador = entrenador;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadorAgregarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.EntrenadoresActualizarResponse VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresActualizar(VistaCliente.ServiceReference.EntrenadoresActualizarRequest request) {
            return base.Channel.EntrenadoresActualizar(request);
        }
        
        public string EntrenadoresActualizar(VistaCliente.ServiceReference.EntrenadorDTO entrenador) {
            VistaCliente.ServiceReference.EntrenadoresActualizarRequest inValue = new VistaCliente.ServiceReference.EntrenadoresActualizarRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresActualizarRequestBody();
            inValue.Body.entrenador = entrenador;
            VistaCliente.ServiceReference.EntrenadoresActualizarResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresActualizar(inValue);
            return retVal.Body.EntrenadoresActualizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresActualizarResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresActualizarAsync(VistaCliente.ServiceReference.EntrenadoresActualizarRequest request) {
            return base.Channel.EntrenadoresActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresActualizarResponse> EntrenadoresActualizarAsync(VistaCliente.ServiceReference.EntrenadorDTO entrenador) {
            VistaCliente.ServiceReference.EntrenadoresActualizarRequest inValue = new VistaCliente.ServiceReference.EntrenadoresActualizarRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresActualizarRequestBody();
            inValue.Body.entrenador = entrenador;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresActualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.EntrenadoresEliminarResponse VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresEliminar(VistaCliente.ServiceReference.EntrenadoresEliminarRequest request) {
            return base.Channel.EntrenadoresEliminar(request);
        }
        
        public string EntrenadoresEliminar(int idEntrenador, string equipo) {
            VistaCliente.ServiceReference.EntrenadoresEliminarRequest inValue = new VistaCliente.ServiceReference.EntrenadoresEliminarRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresEliminarRequestBody();
            inValue.Body.idEntrenador = idEntrenador;
            inValue.Body.equipo = equipo;
            VistaCliente.ServiceReference.EntrenadoresEliminarResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresEliminar(inValue);
            return retVal.Body.EntrenadoresEliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresEliminarResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.EntrenadoresEliminarAsync(VistaCliente.ServiceReference.EntrenadoresEliminarRequest request) {
            return base.Channel.EntrenadoresEliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.EntrenadoresEliminarResponse> EntrenadoresEliminarAsync(int idEntrenador, string equipo) {
            VistaCliente.ServiceReference.EntrenadoresEliminarRequest inValue = new VistaCliente.ServiceReference.EntrenadoresEliminarRequest();
            inValue.Body = new VistaCliente.ServiceReference.EntrenadoresEliminarRequestBody();
            inValue.Body.idEntrenador = idEntrenador;
            inValue.Body.equipo = equipo;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).EntrenadoresEliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.JugadoresListaPorEquipoResponse VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresListaPorEquipo(VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest request) {
            return base.Channel.JugadoresListaPorEquipo(request);
        }
        
        public VistaCliente.ServiceReference.JugadorDTO[] JugadoresListaPorEquipo(string equipo) {
            VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest inValue = new VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresListaPorEquipoRequestBody();
            inValue.Body.equipo = equipo;
            VistaCliente.ServiceReference.JugadoresListaPorEquipoResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresListaPorEquipo(inValue);
            return retVal.Body.JugadoresListaPorEquipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaPorEquipoResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.JugadoresListaPorEquipoAsync(VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest request) {
            return base.Channel.JugadoresListaPorEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.JugadoresListaPorEquipoResponse> JugadoresListaPorEquipoAsync(string equipo) {
            VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest inValue = new VistaCliente.ServiceReference.JugadoresListaPorEquipoRequest();
            inValue.Body = new VistaCliente.ServiceReference.JugadoresListaPorEquipoRequestBody();
            inValue.Body.equipo = equipo;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).JugadoresListaPorEquipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.ListarEquiposResponse VistaCliente.ServiceReference.ServicioFutbolSoap.ListarEquipos(VistaCliente.ServiceReference.ListarEquiposRequest request) {
            return base.Channel.ListarEquipos(request);
        }
        
        public VistaCliente.ServiceReference.ArrayOfString ListarEquipos() {
            VistaCliente.ServiceReference.ListarEquiposRequest inValue = new VistaCliente.ServiceReference.ListarEquiposRequest();
            inValue.Body = new VistaCliente.ServiceReference.ListarEquiposRequestBody();
            VistaCliente.ServiceReference.ListarEquiposResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).ListarEquipos(inValue);
            return retVal.Body.ListarEquiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.ListarEquiposResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.ListarEquiposAsync(VistaCliente.ServiceReference.ListarEquiposRequest request) {
            return base.Channel.ListarEquiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.ListarEquiposResponse> ListarEquiposAsync() {
            VistaCliente.ServiceReference.ListarEquiposRequest inValue = new VistaCliente.ServiceReference.ListarEquiposRequest();
            inValue.Body = new VistaCliente.ServiceReference.ListarEquiposRequestBody();
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).ListarEquiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ServiceReference.ObtenerJugadorPorIdResponse VistaCliente.ServiceReference.ServicioFutbolSoap.ObtenerJugadorPorId(VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest request) {
            return base.Channel.ObtenerJugadorPorId(request);
        }
        
        public VistaCliente.ServiceReference.JugadorDTO ObtenerJugadorPorId(int idJugador) {
            VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest inValue = new VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest();
            inValue.Body = new VistaCliente.ServiceReference.ObtenerJugadorPorIdRequestBody();
            inValue.Body.idJugador = idJugador;
            VistaCliente.ServiceReference.ObtenerJugadorPorIdResponse retVal = ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).ObtenerJugadorPorId(inValue);
            return retVal.Body.ObtenerJugadorPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ServiceReference.ObtenerJugadorPorIdResponse> VistaCliente.ServiceReference.ServicioFutbolSoap.ObtenerJugadorPorIdAsync(VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest request) {
            return base.Channel.ObtenerJugadorPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ServiceReference.ObtenerJugadorPorIdResponse> ObtenerJugadorPorIdAsync(int idJugador) {
            VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest inValue = new VistaCliente.ServiceReference.ObtenerJugadorPorIdRequest();
            inValue.Body = new VistaCliente.ServiceReference.ObtenerJugadorPorIdRequestBody();
            inValue.Body.idJugador = idJugador;
            return ((VistaCliente.ServiceReference.ServicioFutbolSoap)(this)).ObtenerJugadorPorIdAsync(inValue);
        }
    }
}
